function [th] = axticklab(ax,labs,dim,fs)

if nargin==3
    fs = 16;
end

switch(dim)
    case 'y'
        for i=1:length(ax)
            for j=1:length(labs)
                th(i,j) = text( ...
                    min(ax(i).XLim)-0.01*diff(ax(i).XLim), ...
                    ax(i).YTick(j), ...
                    labs{j}, ...
                    'hori','right', ...
                    'verti','mid', ...
                    'fontsize',fs, ...
                    'parent',ax(i));
            end
        end

    case 'x'
        for i=1:length(ax)
            for j=1:length(labs)
                th(i,j) = text( ...
                    ax(i).XTick(j), ...
                    min(ax(i).YLim)-0.01*diff(ax(i).YLim), ...
                    labs{j}, ...
                    'hori','center', ...
                    'verti','top', ...
                    'fontsize',fs, ...
                    'parent',ax(i));
            end
        end        

end